### ISSUE TITLE
Make companies sort ESG by null: 'last'

### ISSUE THREAD

**Issue by daniel-moon32** [toriis-portal/toriis#108]
## Description
Currently the companies that do not have an ESG value are being shown first when sorting from high to low score. Because prisma does not allow for null sorting on a relation. Because of this we need to convert the current company query into a raw mongodb query or something similar

## Learning Objectives

- Objective 1

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [ ] Todo 1

## Useful Links

- Link 1

**Comment by zorazrr** [comment]
This is temporarily resolved with a work-around [here](https://github.com/toriis-portal/toriis/commit/d29d5fa3be8bf06506af9a8855be5c225d93407c#diff-06b142de780b925e650129ceb963a0c834ddbdb0f7077f623c9a527d81de3f83R173), by filtering out all NA values whenever sort by env grade is selected. Leaving this issue open in case we want to revisit this behavior in the future.
