### ISSUE TITLE
Tooltip causes Runtime Error

### ISSUE THREAD

**Issue by eeshabarua** [toriis-portal/toriis#161]
## Description

weird bug from Tooltip shows up randomly after toggling tooltips.

## Todo

These points are a rough guideline. Please feel free to discuss with others on the team about the best way to design this component!

- [x] fix it

## Useful Links

- [Tooltip.tsx error trace](https://github.com/toriis-portal/toriis/blob/7b5a2eda7201613f4715ad8906a6ffa658a79f8a/src/components/Tooltips/ToolTip.tsx#L25-L26)

![image](https://user-images.githubusercontent.com/61480751/235065575-eda34a9d-435d-42e9-8939-9c4d74bf3936.png)

**Comment by kennykos** [comment]
How is this bug triggered?

**Comment by zorazrr** [comment]
This happens when, on specific screens (when you inspect elements specifically I believe, the tooltip on the very right out of the screen border, and hovering on it will cause this error.

**Comment by zorazrr** [comment]
I have a rough idea on how to fix it though I can close it real quick.
